### PR TITLE
add form_with extension

### PR DESCRIPTION
**Pull request by DialBird**
In this PR, I just add a extension for form_with method

### CODE REVIEW

**Comment by amatsuda** [comment]
@DialBird Nice! But would you mind adding a test for this? (Well, I know how messy it is...)

**Comment by DialBird** [comment]
@amatsuda  Thanks for your reply!

I'm sorry to forget adding test!
I'll do it, but I have a problem with testing in my development env, and I can't reveal if it work. (Maybe I can write it by copying `form_for` one, but that's not cool)

In detail, I cant do `bundle exec rake test` after `bundle install`.
Error message is `File does not exist: test/unit/rails/test_help`.
I know what this means, but I cant figure out how can i find or add this file.

I'm so sorry to bother you, but if you not mind, I'd love to ask about it next Asakusa.rb or other event.
How about that?

**Comment by amatsuda** [comment]
@DialBird Of course you can join Asakusa.rb meetup anytime!

**Comment by DialBird** [comment]
As a result, I cant solve the test problem... :(
I wish this would make it !

**Comment by amatsuda** [comment]
@DialBird Thank you!

**Comment by amatsuda** [comment]
Just released 1.9.0 gem including this patch. Thanks!

**Pull request merged**
