### PR TITLE
Problems in model included ActiveModel::Model

### PR DESCRIPTION
**Pull request by ykzts**
## Problems that occur

```ruby
# app/models/item.rb
class Item
  include ActiveModel::Model

  attr_accessor :name, :description
end
```

```ruby
# app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end
end
```

```haml
-# app/views/items/new.html.haml
= form_for @item do |f|
  = f.text_field :name
  = f.text_area :description
```

=>

```
NoMethodError items#new
undefined method `auto_html5_validation' for Item:Class
```

### CODE REVIEW

**Comment by amatsuda** [comment]
@ykzts Oh, wow! Thank you! This apparently has to be a :bug:
Now that we're extending ActiveModel::Model, do you think we still need this? https://github.com/amatsuda/html5_validators/blob/b8491da86c767f75129c7a85540be17ac2d7917f/lib/html5_validators/active_record/base.rb

**Comment by ykzts** [comment]
@amatsuda I think also needless. But, becomes unusable when delete the processing.Do you know workaround?

**Comment by imgarylai** [comment]
#10 It looks like the same problem.

**Comment by amatsuda** [comment]
@ykzts Sorry for not coming back to this issue earlier.
It seems like we cannot remove the AR::Base monkey-patch because AR::Validations finishes including AMo::Validations before we add the accessor to AMo::Validations. 
So let's leave the AR extension as it is.

Thanks again for the fix!

**Comment by amatsuda** [comment]
Published a new :gem: 1.2.2 including this patch.

**Comment by ykzts** [comment]
@amatsuda :dancer::+1:

**Pull request merged**
